### ISSUE TITLE
File Not Found

### ISSUE THREAD

**Issue by corrm** [3F/Conari#11]
![2019-06-30_9-40-28](https://user-images.githubusercontent.com/5868825/60393794-2e04ce80-9b1b-11e9-9f7e-d2f9c37b1bde.png)

my code is just
```csharp
MessageBox.Show(typeof(ConariL).FullName);
```
.Net Target: 4.5

**Comment by 3F** [comment]
Can you illustrate Conari use? We don't know what's inside your `PrintHelper.GetStruct`. Also, Conari 1.3 will never throw `FileNotFoundException` itself.

**Comment by corrm** [comment]
`PrintHelper.GetStruct` contains
```csharp
MessageBox.Show(typeof(ConariL).FullName);
```

**Comment by corrm** [comment]
there is any file must be next to the dll .?
EDIT:
i copied `Conari.dll` in `x86` and `x64` the same problem !!
i use `DllExport` in the same project.

**Comment by corrm** [comment]
SOLVED:
`Conari.dll` must be in the same dir of your exe that's load the dll that's use `DllExport`

**Comment by 3F** [comment]
@CorrM, I'm not sure what are you trying. But you also need to read this: https://msdn.microsoft.com/en-us/library/windows/desktop/ms684179.aspx

And if you're using Conari together with DllExport when unmanaged side is a host side of your application, you can easily specify the any way of searching/loading of all required modules as above.

**Comment by 3F** [comment]
closed due to `SOLVED:` status.

**Comment by 3F** [comment]
.NET DllExport 1.7.1 now provides integration with Conari in "one click". 
There are no more any possible problems with loading the assembly and resolving its types.

https://github.com/3F/DllExport/releases/tag/v1.7.1
> Quick integration with Conari for most easy access to unmanaged features;
> https://github.com/3F/Conari

**Comment by corrm** [comment]
@3F Good work <3.
