### ISSUE TITLE
Support [Guide to add DllExport attribute to my project]

### ISSUE THREAD

**Issue by CGx64** [3F/Conari#16]
I can't add the DllExport attribute to my project, Could you please provide a guide to achieve this?
Thanks a lot.

**Comment by 3F** [comment]
Not sure what do you mean for "add DllExport attribute to my project"

You can use the same way for unmanaged modules if you need also to call an exported methods from managed .NET modules that was marked with [DllExport](https://github.com/3F/DllExport) attribute, like:

```csharp
l.something_with_DllExport_attr<int>(1, 2)
```

or please clarify the question

**Comment by CGx64** [comment]
Hi, @3F please check the next recorded video https://streamable.com/3phcg0 I guess it will be easier to show the problem in this way. Thanks for the quick answer!
I will check the next video in the afternoon https://www.youtube.com/watch?v=sBWt-KdQtoc but I think it was a good idea to add the issue here in case anybody is trying to use Conari but doesn't know DllExport

**Comment by 3F** [comment]
> Hi, @3F please check the next recorded video https://streamable.com/3phcg0 I guess it will be easier to show the problem

I can't connect due to **PR_CONNECT_RESET_ERROR** for `streamable.com`. Please try to use only github and or its gist for some attachments, src, image, etc.

> I think it was a good idea to add the issue here in case anybody is trying to use Conari but doesn't know DllExport

Do you mean https://github.com/3F/DllExport/wiki/PreProc#conari-support or something like https://github.com/3F/DllExport/wiki/Quick-start but for Conari ?

**Comment by 3F** [comment]
Closed due inactivity. Feel free to clarify the case.
