### ISSUE TITLE
Failed loading '...': Check used architecture or existence of file.[Error: 126]

### ISSUE THREAD

**Issue by zy97** [3F/Conari#18]
**Describe the bug**
I have a net5 wpf x32 program that references a dynamic link library where a function opens a dialog box with the current program as its owner, the first call without any problems, but when the dynamic library is re-instantiated later and the call throws an exception like the title
**What code is involved**

![image](https://user-images.githubusercontent.com/20431739/114548691-ae65d680-9c92-11eb-920f-5e1750387028.png)

**Expected behavior**

**Screenshots**

**Comment by 3F** [comment]
126 (0x7E) means specified module could not be found. Including its dependencies and dependencies of each dependency... make sure.

> but when the dynamic library is re-instantiated later and the call throws an exception like the title

Please provide some details how the mentioned "re-instantiated" was implemented there. And how is access going? DlR? lambda?
It would be better to see some demo project to reproduce same error for my machine.

**Comment by zy97** [comment]
Re-instantiation is to new class again inherited from ConariL, and the function of the dynamic link library is operated by the DLR, which, sorry, does not provide demo because it requires a specific environment to invoke the dynamic link library

**Comment by 3F** [comment]
Well I need at least know the hierarchy of the calling for the first requests and the second.

> Re-instantiation is to new class

How? Did you release all resources before new trying?

Also keep this in your mind https://github.com/3F/Conari/issues/15#issue-527765868

btw, 

> inherited from ConariL, and the function of the dynamic link library is operated by the DLR, 

I recommend *ConariX* if DLR is for primary use

**Comment by zy97** [comment]
Thanks for answering my question, now I use  singleton to solve this problem

**Comment by 3F** [comment]
> Thanks for answering my question, now I use singleton to solve this problem

Good! Nice to hear that everything works well!

For everyone, please note the following

* *ConariX* and *ConariL* implements *IDisposable* interface. Disposing *must be* processed with other objects to release all managed and unmanaged resources. *'Where'* and *'How'* depends on specific implementation. To clarify, please use MSDN and so on.

* Starting with 1.4 Conari provides optional isolation between processes according to [https://github.com/3F/Conari/issues/15#issue-527765868](https://github.com/3F/Conari/issues/15#issue-527765868). Configure it through IConfig if you need. See our mta tests for details, for example: 

https://github.com/3F/Conari/blob/7f37c6c5eb2aa28cd49ee7a2963ecdf6fcd44dd5/ConariTest/MtaTest.cs#L17

Also note that starting with 1.5 you will be able provide your custom isolation as needed, for example:

https://github.com/3F/Conari/blob/7f37c6c5eb2aa28cd49ee7a2963ecdf6fcd44dd5/ConariTest/Core/ModuleIsolationRecipeTest.cs#L20

Thanks for using!
