### ISSUE TITLE
The type or namespace name 'DotNet' does not exist

### ISSUE THREAD

**Issue by ssaarian** [3F/Conari#19]
error CS0234: The type or namespace name 'DotNet' does not exist in the namespace 'net.r_eg' (are you missing an assembly reference?)

using net.r_eg.DotNet.System.Reflection.Emit
namespace not found. some module is missing from the Conari-master package

**Comment by 3F** [comment]
Because src requires the following submodule https://github.com/3F/UnmanagedEmitCalli

You can restore it manually via git command or automatically using either VS plugin [vsSolutionBuildEvent](https://github.com/3F/vsSolutionBuildEvent) or just command something like 

> .\build Release

**Comment by 3F** [comment]
Also, 
Do not use the changes from master branch in production code;

I made some new fixes and some important changes (draft version) according to new features and valuable optimizations:

* https://twitter.com/github3F/status/1396491762315808771
* https://twitter.com/github3F/status/1396492298972717057

I'll try push today or tomorrow. Follow the news.

**Comment by 3F** [comment]
1.5 is just out. Feel free to ask anything if you still have the problem. Thanks for using,
